### ISSUE TITLE
Failing at python3 -m fapm --update

### ISSUE THREAD

**Issue by L-udo** [KihariLion/FAPM#1]
running:

python3 -m fapm --update

returns

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ludo/FAPM/fapm/__main__.py", line 22, in <module>
    db.Model.metadata.create_all()
TypeError: MetaData.create_all() missing 1 required positional argument: 'bind'
`

Nobara os (Arch)

**Comment by KihariLion** [comment]
SQLAlchemy 2.0 now requires an explicit `bind` argument for `create_all`, as per https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.MetaData.create_all, which was optional in 1.4.

Thank you for contributing!
